keywords = {
    '#include': 'INCLUSION DIRECTIVE',
    'using': 'KEYWORD',
    'namespace': 'KEYWORD',
    'std': 'NAMESPACE',
    'break': 'KEYWORD',
    'continue': 'KEYWORD',
    'do': 'KEYWORD',
    'while': 'KEYWORD',
    'for': 'KEYWORD',
    'if': 'KEYWORD',
    'else': 'KEYWORD',
    'return': 'KEYWORD',
    'switch': 'KEYWORD',
    'case': 'KEYWORD',
    'default':'KEYWORD',
    'std::swap': 'KEYWORD',
    'private:': 'KEYWORD',
    'public:': 'KEYWORD',
    '(': 'PARENTHESIS',
    ')': 'PARENTHESIS',
    '{': 'PARENTHESIS',
    '}': 'PARENTHESIS',
    '[': 'PARENTHESIS',
    ']': 'PARENTHESIS',
    ',': 'COMA',
    ';': 'END OF CONSTRUCTION',
    'cout': 'OUTPUT',
    'endl': 'OUTPUT MANIPULATOR',
    'vector': 'CONTAINER',
    'list': 'CONTAINER',
    'deque': 'CONTAINER',
    'queue': 'CONTAINER',
    'stack': 'CONTAINER',
    'set': 'CONTAINER',
    'unordered_set': 'CONTAINER',
    'multiset': 'CONTAINER',
    'map': 'CONTAINER',
    'unordered_map': 'CONTAINER',
    'multimap': 'CONTAINER',
    'bitset': 'CONTAINER',
    'class': 'KEYWORD',
    'struct': 'KEYWORD',
    'const': 'KEYWORD'
}

operators = {
    '//': 'COMMENT',
    '/*': 'COMMENT',
    '*/': 'COMMENT',
    '->': 'POINTER',
    '.': 'OPERATOR',
    '+': 'ARITHMETIC OPERATOR',
    '-': 'ARITHMETIC OPERATOR',
    '*': 'ARITHMETIC OPERATOR',
    '/': 'ARITHMETIC OPERATOR',
    '%': 'ARITHMETIC OPERATOR',
    '++': 'ARITHMETIC OPERATOR',
    '--': 'ARITHMETIC OPERATOR',
    '+=': 'ARITHMETIC OPERATOR',
    '-=': 'ARITHMETIC OPERATOR',
    '*=': 'ARITHMETIC OPERATOR',
    '/=': 'ARITHMETIC OPERATOR',
    '%=': 'ARITHMETIC OPERATOR',
    '=': 'ADDIGNMENT OPERATOR',
    'pow': 'FUNCTION',
    'sqrt': 'FUNCTION',
    'sin': 'FUNCTION',
    'cos': 'FUNCTION',
    'log': 'FUNCTION',
    'exp': 'FUNCTION',
    'round': 'FUNCTION',
    '==': 'COMPARISON OPERATOR',
    '!=': 'COMPARISON OPERATOR',
    '<': 'COMPARISON OPERATOR',
    '>': 'COMPARISON OPERATOR',
    '<=': 'COMPARISON OPERATOR',
    '>=': 'COMPARISON OPERATOR',
    '>>': 'BITWISE OPERATOR',
    '<<': 'BITWISE OPERATOR',
    '<<': 'I/O OPERATOR',
    '>>': 'I/O OPERATOR',
    '&&': 'LOGICAL OPERATOR',
    '||': 'LOGICAL OPERATOR',
    '!': 'LOGICAL OPERATOR',
    '&': 'BITWISE OPERATOR',
    '|': 'BITWISE OPERATOR',
    '^': 'BITWISE OPERATOR',
    '~': 'BITWISE OPERATOR',
    '?': 'TERNARY OPERATOR'
}

data_types = {
    'bool': 'DATA TYPE',
    'signed char': 'DATA TYPE',
    'void': 'DATA TYPE',
    'char': 'DATA TYPE',
    'short': 'DATA TYPE',
    'int': 'DATA TYPE',
    'long': 'DATA TYPE',
    'long long': 'DATA TYPE',
    'unsigned char': 'DATA TYPE',
    'unsigned short': 'DATA TYPE',
    'unsigned int': 'DATA TYPE',
    'unsigned long': 'DATA TYPE',
    'unsigned long long': 'DATA TYPE',
    'float': 'DATA TYPE',
    'double': 'DATA TYPE',
    'long double': 'DATA TYPE',
    'wchar_t': 'DATA TYPE',
    'char8_t': 'DATA TYPE',
    'char16_t': 'DATA TYPE',
    'char32_t': 'DATA TYPE',
    'std::string': 'DATA TYPE',
}